version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/cert.crt:/etc/nginx/cert.crt
      - ./certs/cert.key:/etc/nginx/cert.key
    ports:
      - 443:443
    depends_on:
      - web
    restart: always
    networks:
      - botiumBox
  web:
    image: botium/botium-box-server:2.1.0
    ports:
     - "4000:4000"
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/box/prod13
      BOTIUMBOX_QUEUE_REDISURL: redis://redis:6379
      ZAP_ENDPOINT: http://zap:8080
      DEBUG: botium*
      TESTSETDIR_PUBLIC: ./testsets
      #HTTP_PROXY: https://xxx
      #HTTPS_PROXY: https://xxx
      #NO_PROXY: redis,prisma
      #NODE_TLS_REJECT_UNAUTHORIZED: 0
    depends_on:
      - redis
      - prisma
    restart: always
    volumes:
      - "./testsets:/app/server/testsets"
      - "./resources:/app/server/resources"
      - "./botiumwork:/app/server/botiumwork"
    networks:
      - botiumBox
  agent:
    image: botium/botium-box-agent:2.1.0
    environment:
      BOTIUMBOX_QUEUE_REDISURL: redis://redis:6379
      DEBUG: botium*
      #HTTP_PROXY: https://xxx
      #HTTPS_PROXY: https://xxx
      #NO_PROXY: redis,prisma
      #NODE_TLS_REJECT_UNAUTHORIZED: 0
    depends_on:
      - web
      - redis
    restart: always
    volumes:
      - "./testsets:/app/agent/testsets"
      - "./resources:/app/agent/resources"
      - "./botiumwork:/app/agent/botiumwork"
    networks:
      - botiumBox
  prisma:
    image: prismagraphql/prisma:1.34.10
    depends_on:
      - mysql
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    networks:
      - botiumBox
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - botiumBox
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    restart: always
    links:
      - mysql:db
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - "4001:80"
    networks:
      - botiumBox
  redis:
    image: redis:alpine
    restart: always
    networks:
      - botiumBox
  zap:
    image: owasp/zap2docker-stable:2.7.0
    command: [
      "zap.sh",
      "-daemon",
      "-host", "0.0.0.0", "-port", "8080",
      "-config", "api.disablekey=true",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true"
    ]
    networks:
      - botiumBox
networks:
  botiumBox:
