apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zap-pv-claim
  namespace: botium-box
  labels:
    name: zap-pv-claim
    app: botium-box
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: botium-box
  labels:
    name: zap
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: zap
      app: botium-box
      tier: backend
  template:
    metadata:
      labels:
        name: zap
        app: botium-box
        tier: backend
    spec:
      containers:
      - name: zap
        image: owasp/zap2docker-stable:latest
        command: [
          "zap.sh",
          "-daemon",
          "-host", "0.0.0.0", "-port", "8080",
          "-config", "api.disablekey=true",
          "-config", "api.addrs.addr.name=.*",
          "-config", "api.addrs.addr.regex=true",
          "-dir", "/data"
        ]
        ports:
          - name: zap-8080
            containerPort: 8080
        volumeMounts:
        - name: zap-persistent-storage
          mountPath: /data
      volumes:
      - name: zap-persistent-storage
        persistentVolumeClaim:
          claimName: zap-pv-claim               
---
apiVersion: v1
kind: Service
metadata:
  name: zap
  namespace: botium-box
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: zap
    app: botium-box