apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: botium-box
  labels:
    name: redis-pv-claim
    app: botium-box
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: botium-box
  labels:
    name: redis
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: redis
      app: botium-box
      tier: backend
  template:
    metadata:
      labels:
        name: redis
        app: botium-box
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - name: redis-6379
          containerPort: 6379
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim              
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: botium-box
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    name: redis
    app: botium-box